package sbnz.integracija

import sbnz.integracija.example.facts.Zapisnik;
import sbnz.integracija.example.facts.KaznaVoznjaPodUticajem;

import java.util.List
import java.util.ArrayList

global List lista;
global List pravilo2;
global List pravilo3;

rule "pod uticajem psihoaktivnih supstanci"
agenda-group "modul1"
salience 97
	when
		$z: Zapisnik( prisustvoPsihoaktivnihSupstanci == true, voznjaPodUticajem == null )
	then
		KaznaVoznjaPodUticajem k = new KaznaVoznjaPodUticajem();
		k.setTip(KaznaVoznjaPodUticajem.TipVoznjePodUticajem.PSIHOAKTIVNA_SUPS);
        k.setObradjena(false);
        k.setClan(null);

        insert(k);
		modify($z) { setVoznjaPodUticajem(k) }
end