package sbnz.integracija

import sbnz.integracija.example.facts.Zapisnik;
import sbnz.integracija.example.facts.KaznaPrekoracenjaBrzine;
import sbnz.integracija.example.facts.Kazna;
import java.time.LocalTime;

import java.util.List
import java.util.ArrayList

global List lista;
global List pravilo2;
global List pravilo3;

rule "prekoracenje vece od 60 km/h u zoni skole"
agenda-group "modul1"
salience 19
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 60, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_330) }
end

rule "prekoracenje od 51 do 60 km/h u zoni skole"
agenda-group "modul1"
salience 18
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 50, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_331),
            setKazneniPoeni(6),
            setZabranaUpravljanja(5)
        }
end

rule "prekoracenje od 31 do 50 km/h u zoni skole"
agenda-group "modul1"
salience 17
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 30, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_332),
            setKazneniPoeni(4),
            setZabranaUpravljanja(2)
        }
end

rule "prekoracenje od 21 do 30 km/h u zoni skole"
agenda-group "modul1"
salience 16
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 20, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_332a) }
end

rule "prekoracenje od 11 do 20 km/h u zoni skole"
agenda-group "modul1"
salience 15
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 10, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_333) }
end

rule "prekoracenje do 10 km/h u zoni skole"
agenda-group "modul1"
salience 14
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_SKOLE, vreme != null, vreme.isAfter(LocalTime.parse("06:59:59")), vreme.isBefore(LocalTime.parse("21:00:01")) )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 0, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_334) }
end