package sbnz.integracija

import sbnz.integracija.example.facts.Zapisnik;
import sbnz.integracija.example.facts.KaznaPrekoracenjaBrzine;
import sbnz.integracija.example.facts.Kazna;

rule "kazna za nasilnicku voznju"
agenda-group "modul1"
salience 20
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 90, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_329) }
end

rule "prekoracenje od 71 do 90 km/h"
agenda-group "modul1"
salience -1
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 70, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_330) }
end

rule "prekoracenje od 51 do 70 km/h"
agenda-group "modul1"
salience -2
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 50, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_331),
            setKazneniPoeni(7),
            setZabranaUpravljanja(4)
        }
end

rule "prekoracenje od 31 do 50 km/h"
agenda-group "modul1"
salience -3
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 30, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_332),
            setKazneniPoeni(4),
            setZabranaUpravljanja(1)
        }
end

rule "prekoracenje od 21 do 30 km/h"
agenda-group "modul1"
salience -4
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 20, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_332a) }
end

rule "prekoracenje od 11 do 20 km/h"
agenda-group "modul1"
salience -5
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 10, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_333) }
end

rule "prekoracenje do 10 km/h"
agenda-group "modul1"
salience -6
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, naseljenoMesto == true )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 0, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_334) }
end
