package sbnz.integracija

import sbnz.integracija.example.facts.Zapisnik;
import sbnz.integracija.example.facts.KaznaPrekoracenjaBrzine;
import sbnz.integracija.example.facts.Kazna;

rule "prekoracenje vece od 50 km/h u zoni usporenog saobracaja"
    salience 19
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_USPORENOG_SAOBRACAJA )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 50, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_330) }
end

rule "prekoracenje od 31 do 50 km/h u zoni usporenog saobracaja"
salience 18
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_USPORENOG_SAOBRACAJA )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 30, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_331),
            setKazneniPoeni(4),
            setZabranaUpravljanja(3)
        }
end

rule "prekoracenje od 10 do 30 km/h u zoni usporenog saobracaja"
salience 17
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_USPORENOG_SAOBRACAJA )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 10, clan == null )
    then
        modify($k) {
            setClan(Kazna.Clanovi.CLAN_332),
            setKazneniPoeni(2)
        }
end

rule "prekoracenje do 10 km/h u zoni usporenog saobracaja"
salience 16
    when
        $z: Zapisnik( $kazna: prekoracenjeBrzine, zona == Zapisnik.Zona.ZONA_USPORENOG_SAOBRACAJA )
        $k: KaznaPrekoracenjaBrzine( this == $kazna, iznosPrekoracenja > 0, clan == null )
    then
        modify($k) { setClan(Kazna.Clanovi.CLAN_333) }
end